#!/bin/sh

export G_SLICE=always-malloc
export G_DEBUG=gc-friendly
/usr/bin/valgrind \
	--leak-check=full \
	--suppressions=test/pango.supp \
	--suppressions=test/suppressions/glib.supp \
	--suppressions=test/suppressions/gtk.supp \
	--suppressions=test/suppressions/mesa.supp \
	--suppressions=test/suppressions/fm.supp \
	--suppressions=test/suppressions/samplecat.supp \
	--gen-suppressions=yes \
	--num-callers=50 \
	$@ ./src/samplecat
