#!/bin/sh

container=samplecat-ubuntu-18

# run git build script
#docker run -it $container

# run the container and run a specific command (overrides CMD)
#docker run -it $container bash

# run with X forwarding
#XSOCK=/tmp/.X11-unix/X0 docker run -it -v $XSOCK:$XSOCK $container bash

# privileged is needed for opengl
#             docker run --privileged -e "DISPLAY=unix:0.0" -v="/tmp/.X11-unix:/tmp/.X11-unix:rw" -i -t $container bash
docker run --privileged -v="/tmp/.X11-unix:/tmp/.X11-unix:rw" -i -t $container bash
