/* dock-item.vapi generated by valac-0.56 0.56.17, do not modify. */

[CCode (cheader_filename = "stdint.h", cprefix = "", lower_case_cprefix = "")]
public class DockItem : Gtk.Widget, Gtk.ShortcutManager {
	public bool property1;
	public DockItem ();
	public override void unrealize ();
}
