/* filemanager.c generated by valac 0.12.1, the Vala compiler
 * generated from filemanager.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <file_manager/file_manager.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>


#define AYYI_TYPE_LIBFILEMANAGER (ayyi_libfilemanager_get_type ())
#define AYYI_LIBFILEMANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AYYI_TYPE_LIBFILEMANAGER, AyyiLibfilemanager))
#define AYYI_LIBFILEMANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AYYI_TYPE_LIBFILEMANAGER, AyyiLibfilemanagerClass))
#define AYYI_IS_LIBFILEMANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AYYI_TYPE_LIBFILEMANAGER))
#define AYYI_IS_LIBFILEMANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AYYI_TYPE_LIBFILEMANAGER))
#define AYYI_LIBFILEMANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AYYI_TYPE_LIBFILEMANAGER, AyyiLibfilemanagerClass))

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _XAyyiLibfilemanager {
	GObject parent_instance;
	AyyiLibfilemanagerPrivate * priv;
	struct _Filer* file_window;
};

struct _XAyyiLibfilemanagerClass {
	GObjectClass parent_class;
};


static gpointer ayyi_libfilemanager_parent_class = NULL; 
extern char theme_name[];

GType ayyi_libfilemanager_get_type (void) G_GNUC_CONST;
enum  {
	AYYI_LIBFILEMANAGER_DUMMY_PROPERTY
};
AyyiLibfilemanager* ayyi_libfilemanager_new (struct _Filer* _file_window);
AyyiLibfilemanager* ayyi_libfilemanager_construct (GType object_type, struct _Filer* _file_window);
GtkWidget* ayyi_libfilemanager_new_window (AyyiLibfilemanager* self, const gchar* path);
void ayyi_libfilemanager_emit_dir_changed (AyyiLibfilemanager* self);
static GObject * ayyi_libfilemanager_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void ayyi_libfilemanager_finalize (GObject* obj);


AyyiLibfilemanager* ayyi_libfilemanager_construct (GType object_type, struct _Filer* _file_window) {
	AyyiLibfilemanager * self = NULL;
	self = (AyyiLibfilemanager*) g_object_new (object_type, NULL);
	self->file_window = _file_window;
	return self;
}


AyyiLibfilemanager* ayyi_libfilemanager_new (struct _Filer* _file_window) {
	return ayyi_libfilemanager_construct (AYYI_TYPE_LIBFILEMANAGER, _file_window);
}


GtkWidget* ayyi_libfilemanager_new_window (AyyiLibfilemanager* self, const gchar* path) {
	GtkWidget* result = NULL;
	GtkWidget* w;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	w = NULL;
	filer_update_dir (self->file_window, TRUE);
	result = w;
	return result;
}


void ayyi_libfilemanager_emit_dir_changed (AyyiLibfilemanager* self) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "dir-changed", (*self->file_window).real_path);
}


static GObject * ayyi_libfilemanager_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	AyyiLibfilemanager * self;
	parent_class = G_OBJECT_CLASS (ayyi_libfilemanager_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = AYYI_LIBFILEMANAGER (obj);
	return obj;
}


static void ayyi_libfilemanager_class_init (AyyiLibfilemanagerClass * klass) {
	ayyi_libfilemanager_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->constructor = ayyi_libfilemanager_constructor;
	G_OBJECT_CLASS (klass)->finalize = ayyi_libfilemanager_finalize;
	g_signal_new ("dir_changed", AYYI_TYPE_LIBFILEMANAGER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
}


static void ayyi_libfilemanager_instance_init (AyyiLibfilemanager * self) {
}


static void ayyi_libfilemanager_finalize (GObject* obj) {
	AyyiLibfilemanager * self;
	self = AYYI_LIBFILEMANAGER (obj);
	G_OBJECT_CLASS (ayyi_libfilemanager_parent_class)->finalize (obj);
}


GType ayyi_libfilemanager_get_type (void) {
	static volatile gsize ayyi_libfilemanager_type_id__volatile = 0;
	if (g_once_init_enter (&ayyi_libfilemanager_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AyyiLibfilemanagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ayyi_libfilemanager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AyyiLibfilemanager), 0, (GInstanceInitFunc) ayyi_libfilemanager_instance_init, NULL };
		GType ayyi_libfilemanager_type_id;
		ayyi_libfilemanager_type_id = g_type_register_static (G_TYPE_OBJECT, "AyyiLibfilemanager", &g_define_type_info, 0);
		g_once_init_leave (&ayyi_libfilemanager_type_id__volatile, ayyi_libfilemanager_type_id);
	}
	return ayyi_libfilemanager_type_id__volatile;
}



