/* filemanager.h generated by valac 0.12.1, the Vala compiler, do not modify */


#ifndef __FILEMANAGER_H__
#define __FILEMANAGER_H__

#include <glib.h>
#include <glib-object.h>
#include <file_manager/file_manager.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>

G_BEGIN_DECLS


#define AYYI_TYPE_LIBFILEMANAGER (ayyi_libfilemanager_get_type ())
#define AYYI_LIBFILEMANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AYYI_TYPE_LIBFILEMANAGER, AyyiLibfilemanager))
#define AYYI_LIBFILEMANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AYYI_TYPE_LIBFILEMANAGER, AyyiLibfilemanagerClass))
#define AYYI_IS_LIBFILEMANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AYYI_TYPE_LIBFILEMANAGER))
#define AYYI_IS_LIBFILEMANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AYYI_TYPE_LIBFILEMANAGER))
#define AYYI_LIBFILEMANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AYYI_TYPE_LIBFILEMANAGER, AyyiLibfilemanagerClass))

typedef struct _AyyiLibfilemanager AyyiLibfilemanager;
typedef struct _AyyiLibfilemanagerClass AyyiLibfilemanagerClass;
typedef struct _AyyiLibfilemanagerPrivate AyyiLibfilemanagerPrivate;

struct _AyyiLibfilemanager {
	GObject parent_instance;
	AyyiLibfilemanagerPrivate * priv;
	struct _Filer* file_window;
};

struct _AyyiLibfilemanagerClass {
	GObjectClass parent_class;
};


GType ayyi_libfilemanager_get_type (void) G_GNUC_CONST;
AyyiLibfilemanager* ayyi_libfilemanager_new (struct _Filer* _file_window);
AyyiLibfilemanager* ayyi_libfilemanager_construct (GType object_type, struct _Filer* _file_window);
GtkWidget* ayyi_libfilemanager_new_window (AyyiLibfilemanager* self, const gchar* path);
void ayyi_libfilemanager_emit_dir_changed (AyyiLibfilemanager* self);


G_END_DECLS

#endif
