#!/bin/sh

image=samplecat-debian-10

usage="run [OPTIONS]\n\noptions:\n  -i interactive (bash shell)\n\nWithout options, default samplecat build will run\n"

branch=${CI_COMMIT_BRANCH:-master}

while getopts ":i" opt; do
    case $opt in
        i  )
			# run with X forwarding
			# (dont forget to run xhost to allow the container to connect)
			# privileged is needed for opengl
			#             docker run --privileged -e "DISPLAY=unix:0.0" -v="/tmp/.X11-unix:/tmp/.X11-unix:rw" -i -t $image bash
			docker run --privileged -v="/tmp/.X11-unix:/tmp/.X11-unix:rw" -e DISPLAY=$DISPLAY -i -t $image bash
			exit
			;;
        \? ) echo -e $usage
            exit 1
    esac
done
shift $(($OPTIND - 1))

test -t 1 && USE_TTY="-t"

# run git build script
docker run --rm -e BRANCH="$branch" -e DISPLAY=$DISPLAY -i ${USE_TTY} $image
