#!/bin/sh

container=samplecat-ubuntu-16

usage="run [OPTIONS]\n\noptions:\n  -i interactive (bash shell)\n\nWithout options, default samplecat build will run\n"

while getopts ":i" opt; do
    case $opt in
        i  )
			# privileged is needed for opengl
			#             docker run --privileged -e "DISPLAY=unix:0.0" -v="/tmp/.X11-unix:/tmp/.X11-unix:rw" -i -t $container bash
			docker run --rm --privileged -v="/tmp/.X11-unix:/tmp/.X11-unix:rw" -i -t $container bash
			exit
			;;
        \? ) echo -e $usage
            exit 1
    esac
done
shift $(($OPTIND - 1))

# run git build script
docker run --rm -it $container

# run the container and run a specific command (overrides CMD)
#docker run -it $container bash

# run with X forwarding
#XSOCK=/tmp/.X11-unix/X0 docker run -it -v $XSOCK:$XSOCK $container bash
