FROM fedora:34

RUN dnf -y update && \
	dnf -y install \\

#include "dependencies"

RUN echo "alias ll='ls -l'" >> /root/.bashrc
WORKDIR /root
ADD scripts/add_samples /root/
ADD scripts/Makefile /root/

CMD make
