#!/bin/sh

container=samplecat-fedora-34

usage="run [OPTIONS]\n\noptions:\n  -i interactive (bash shell)\n\nWithout options, default samplecat build will run\n"

branch=${CI_COMMIT_BRANCH:-master}

test -t 1 && TTY="-t"

while getopts ":i" opt; do
    case $opt in
        i  )
			if [ -e $TTY ]
			then
				echo cannot run interactive container without tty
				exit
			fi
			docker run --rm --privileged -v="/tmp/.X11-unix:/tmp/.X11-unix:rw" -e DISPLAY=$DISPLAY -i -t $container bash
			exit
			;;
        \? ) echo -e $usage
            exit 1
    esac
done
shift $(($OPTIND - 1))

# run git build script
docker run --rm -e branch="$branch" -e DISPLAY=$DISPLAY -i ${TTY} $container
