/* table.h generated by valac 0.16.0, the Vala compiler, do not modify */


#ifndef __TABLE_H__
#define __TABLE_H__

#include <glib.h>
#include <glib-object.h>
#include <webkit/webkit.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define TYPE_TABLE (table_get_type ())
#define TABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TABLE, Table))
#define TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TABLE, TableClass))
#define IS_TABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TABLE))
#define IS_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TABLE))
#define TABLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TABLE, TableClass))

typedef struct _Table Table;
typedef struct _TableClass TableClass;
typedef struct _TablePrivate TablePrivate;

struct _Table {
	GObject parent_instance;
	TablePrivate * priv;
	WebKitDOMElement* el;
	WebKitDOMElement* tbody;
	WebKitDOMElement* thead;
};

struct _TableClass {
	GObjectClass parent_class;
};


GType table_get_type (void) G_GNUC_CONST;
extern WebKitDOMDocument* table_document;
Table* table_new (WebKitDOMElement* parent, const gchar* id);
Table* table_construct (GType object_type, WebKitDOMElement* parent, const gchar* id);


G_END_DECLS

#endif
