#!/bin/sh

container=samplecat-ubuntu-14

# run git build script
docker run -it $container

# run the container and run a specific command (overrides CMD)
#docker run -it $container bash

# run with X forwarding
#XSOCK=/tmp/.X11-unix/X0 docker run -it -v $XSOCK:$XSOCK $container bash
