#!/bin/sh

container=$(cat name)

# run with X forwarding
#XSOCK=/tmp/.X11-unix/X0 docker run -it -v $XSOCK:$XSOCK $container bash


usage="run [OPTIONS]\n\noptions:\n  -i interactive (bash shell)\n\nWithout options, default samplecat build will run\n"

if [ -z "$CI_COMMIT_BRANCH" ]
then
	branch=master
else
	branch="$CI_COMMIT_BRANCH"
fi

test -t 1 && TTY="-t"

if [ ! -e $TTY ]
then
	display='-e "DISPLAY=unix:0.0"'
fi

while getopts ":i" opt; do
    case $opt in
        i  )
			if [ -e $TTY ]
			then
				echo cannot run interactive container without tty
				exit 1
			fi
			# - privileged is needed for opengl
			docker run --rm --privileged $display -v="/tmp/.X11-unix:/tmp/.X11-unix:rw" -i -t $container bash
			exit
			;;
        \? ) echo -e $usage
            exit 1
    esac
done
shift $(($OPTIND - 1))

CI_COMMIT_BRANCH=${CI_COMMIT_BRANCH:-master}

# run git build script
docker run --rm -e branch="$branch" -i $display $TTY $container
