---
dock:
  name: __dock_1
  floating: no
  width: '-1'
  height: '-1'
  floatx: '0'
  floaty: '0'
  paned:
    position: '70'
    item:
      name: Search
      locked: 'yes'
    paned:
	  orientation: horizontal
      position: '275'
      paned:
        position: '159'
        paned:
          position: '101'
          item:
            name: Tags
          item:
            name: Filters
        paned:
          position: '197'
          item:
            name: Directories
          item:
            name: Inspector
      paned:
        position: '443'
        notebook:
          page: 1
          item:
            name: Filemanager
          item:
            name: Library
        item:
          name: Waveform
...
