/* list_store.c generated by valac 0.12.1, the Vala compiler
 * generated from list_store.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk-pixbuf/gdk-pixdata.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <sample.h>
#include <listmodel.h>
#include <support.h>
#include <overview.h>


#define SAMPLECAT_TYPE_LIST_STORE (samplecat_list_store_get_type ())
#define SAMPLECAT_LIST_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SAMPLECAT_TYPE_LIST_STORE, SamplecatListStore))
#define SAMPLECAT_LIST_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SAMPLECAT_TYPE_LIST_STORE, SamplecatListStoreClass))
#define SAMPLECAT_IS_LIST_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SAMPLECAT_TYPE_LIST_STORE))
#define SAMPLECAT_IS_LIST_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SAMPLECAT_TYPE_LIST_STORE))
#define SAMPLECAT_LIST_STORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SAMPLECAT_TYPE_LIST_STORE, SamplecatListStoreClass))


struct _SamplecatListStoreX {
	GtkListStore parent_instance;
	SamplecatListStorePrivate * priv;
};

struct _SamplecatListStoreClassX {
	GtkListStoreClass parent_class;
};


static gpointer samplecat_list_store_parent_class = NULL;

GType samplecat_list_store_get_type (void) G_GNUC_CONST;
enum  {
	SAMPLECAT_LIST_STORE_DUMMY_PROPERTY
};
SamplecatListStore* samplecat_list_store_new (void);
SamplecatListStore* samplecat_list_store_construct (GType object_type);
void samplecat_list_store_add (SamplecatListStore* self, Sample* sample);
void samplecat_list_store_do_search (SamplecatListStore* self);


SamplecatListStore* samplecat_list_store_construct (GType object_type) {
	SamplecatListStore * self = NULL;
	GType _tmp0_[13] = {0};
	GType types[13];
	self = (SamplecatListStore*) g_object_new (object_type, NULL);
	_tmp0_[0] = GDK_TYPE_PIXBUF;
	_tmp0_[1] = G_TYPE_INT;
	_tmp0_[2] = G_TYPE_STRING;
	_tmp0_[3] = G_TYPE_STRING;
	_tmp0_[4] = G_TYPE_STRING;
	_tmp0_[5] = GDK_TYPE_PIXBUF;
	_tmp0_[6] = G_TYPE_STRING;
	_tmp0_[7] = G_TYPE_STRING;
	_tmp0_[8] = G_TYPE_INT;
	_tmp0_[9] = G_TYPE_STRING;
	_tmp0_[10] = G_TYPE_FLOAT;
	_tmp0_[11] = G_TYPE_INT;
	_tmp0_[12] = G_TYPE_POINTER;
	memcpy (types, _tmp0_, 13 * sizeof (GType));
	gtk_list_store_set_column_types ((GtkListStore*) self, 13, types);
	return self;
}


SamplecatListStore* samplecat_list_store_new (void) {
	return samplecat_list_store_construct (SAMPLECAT_TYPE_LIST_STORE);
}


void samplecat_list_store_add (SamplecatListStore* self, Sample* sample) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	listmodel__add_result (sample);
	if (!((gboolean) (*sample).ebur)) {
		_tmp1_ = TRUE;
	} else {
		gsize _tmp2_;
		_tmp2_ = strlen ((const gchar*) (*sample).ebur);
		_tmp1_ = !((gboolean) _tmp2_);
	}
	if (_tmp1_) {
		_tmp0_ = (gboolean) (*sample).row_ref;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		dbg (1, "regenerate ebur128");
		request_ebur128 (sample);
	}
	sample_ref (sample);
}


void samplecat_list_store_do_search (SamplecatListStore* self) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "content-changed");
}


static void samplecat_list_store_class_init (SamplecatListStoreClass * klass) {
	samplecat_list_store_parent_class = g_type_class_peek_parent (klass);
	g_signal_new ("content_changed", SAMPLECAT_TYPE_LIST_STORE, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void samplecat_list_store_instance_init (SamplecatListStore * self) {
}


GType samplecat_list_store_get_type (void) {
	static volatile gsize samplecat_list_store_type_id__volatile = 0;
	if (g_once_init_enter (&samplecat_list_store_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SamplecatListStoreClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) samplecat_list_store_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SamplecatListStore), 0, (GInstanceInitFunc) samplecat_list_store_instance_init, NULL };
		GType samplecat_list_store_type_id;
		samplecat_list_store_type_id = g_type_register_static (GTK_TYPE_LIST_STORE, "SamplecatListStore", &g_define_type_info, 0);
		g_once_init_leave (&samplecat_list_store_type_id__volatile, samplecat_list_store_type_id);
	}
	return samplecat_list_store_type_id__volatile;
}



