/* list_store.h generated by valac 0.12.1, the Vala compiler, do not modify */


#ifndef __LIST_STORE_H__
#define __LIST_STORE_H__

#include <glib.h>
#include <gtk/gtk.h>
#include <sample.h>

G_BEGIN_DECLS


#define SAMPLECAT_TYPE_LIST_STORE (samplecat_list_store_get_type ())
#define SAMPLECAT_LIST_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SAMPLECAT_TYPE_LIST_STORE, SamplecatListStore))
#define SAMPLECAT_LIST_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SAMPLECAT_TYPE_LIST_STORE, SamplecatListStoreClass))
#define SAMPLECAT_IS_LIST_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SAMPLECAT_TYPE_LIST_STORE))
#define SAMPLECAT_IS_LIST_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SAMPLECAT_TYPE_LIST_STORE))
#define SAMPLECAT_LIST_STORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SAMPLECAT_TYPE_LIST_STORE, SamplecatListStoreClass))

typedef struct _SamplecatListStore SamplecatListStore;
typedef struct _SamplecatListStoreClass SamplecatListStoreClass;
typedef struct _SamplecatListStorePrivate SamplecatListStorePrivate;

struct _SamplecatListStore {
	GtkListStore parent_instance;
	SamplecatListStorePrivate * priv;
};

struct _SamplecatListStoreClass {
	GtkListStoreClass parent_class;
};


GType samplecat_list_store_get_type (void) G_GNUC_CONST;
SamplecatListStore* samplecat_list_store_new (void);
SamplecatListStore* samplecat_list_store_construct (GType object_type);
void samplecat_list_store_add (SamplecatListStore* self, Sample* sample);
void samplecat_list_store_do_search (SamplecatListStore* self);


G_END_DECLS

#endif
