/* model.h generated by valac 0.20.1, the Vala compiler, do not modify */


#ifndef __MODEL_H__
#define __MODEL_H__

#include <glib.h>
#include <glib-object.h>
#include <sample.h>

G_BEGIN_DECLS


#define SAMPLECAT_TYPE_FILTERS (samplecat_filters_get_type ())
typedef struct _SamplecatFilters SamplecatFilters;

#define SAMPLECAT_TYPE_MODEL (samplecat_model_get_type ())
#define SAMPLECAT_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SAMPLECAT_TYPE_MODEL, SamplecatModel))
#define SAMPLECAT_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SAMPLECAT_TYPE_MODEL, SamplecatModelClass))
#define SAMPLECAT_IS_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SAMPLECAT_TYPE_MODEL))
#define SAMPLECAT_IS_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SAMPLECAT_TYPE_MODEL))
#define SAMPLECAT_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SAMPLECAT_TYPE_MODEL, SamplecatModelClass))

typedef struct _SamplecatModelClass SamplecatModelClass;
typedef struct _SamplecatModelPrivate SamplecatModelPrivate;

struct _SamplecatFilters {
	gchar phrase[256];
	gchar* dir;
	gchar* category;
};

struct _SamplecatModel {
	GObject parent_instance;
	SamplecatModelPrivate * priv;
	gint state;
	gchar* cache_dir;
	SamplecatFilters filters;
	Sample* selection;
};

struct _SamplecatModelClass {
	GObjectClass parent_class;
};


GType samplecat_filters_get_type (void) G_GNUC_CONST;
SamplecatFilters* samplecat_filters_dup (const SamplecatFilters* self);
void samplecat_filters_free (SamplecatFilters* self);
GType samplecat_model_get_type (void) G_GNUC_CONST;
SamplecatModel* samplecat_model_new (void);
SamplecatModel* samplecat_model_construct (GType object_type);
void samplecat_model_set_search_dir (SamplecatModel* self, gchar* dir);
void samplecat_model_set_selection (SamplecatModel* self, Sample* sample);


G_END_DECLS

#endif
